name: Asterisk
avatar: images/asterisk_ext.png # Avatar image. Default to "images/profile.webp".
bio: 'Canadian Linux Nerd'
# company:  # HTML markup are supported, such as: <a href="https://example.com" target="_blank" rel="noopener noreferrer">Company</a>.
location: <a href="https://en.wikipedia.org/wiki/Canada" target="_blank" rel="noopener noreferrer">Canada</a> # HTML markup are supported, such as: <a href='https://www.openstreetmap.org/search?query=Earth'>Earth</a>.
# about: https://asterisk.shinken.studio/#about # The external about page. The internal about page will be used if not set.
params: {
  # layout: compact
}
# See https://hbs.razonyang.com/v1/en/docs/widgets/social-links/.
social:
  website: https://asterisk.shinken.studio
  email: contact.asterisk@shinken.studio
  github: ast3risk-ops
  # twitter:
  # patreon: razonyang
  # paypal: razonyang
  rss: "default.xml" # Remove RSS
