main:
  - name: Source Code
    identifier: source
    url: https://github.com/ast3risk-ops/blog
    params:
      icon: '<i class="fab fa-github"></i>'
  - name: My Website
    identifier: site
    url: https://asterisk.shinken.studio
    params:
      icon: '<i class="fas fa-globe"></i>'
